name: flutter_starter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  go_router: ^14.2.0
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.3
  flutter_launcher_icons: ^0.13.1
  flutter_easyloading: ^3.0.5
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.2.3
  dartz: ^0.10.1
  pretty_dio_logger: ^1.3.1
  get_it: ^7.7.0
  flutter_gen: ^5.6.0
  injectable: ^2.4.2
  dio: ^5.4.3+1
  toastification: ^2.2.0
  pin_code_fields: ^8.0.1
  rename: ^3.0.2
  flutter:
    sdk: flutter

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    lottie: true

  assets:
    enabled: true

    outputs:
      class_name: Assets
      package_parameter_enabled: false
      output: lib/gen/assets.gen.dart

      style: dot-delimiter

    exclude:
      - assets/logo/
      - assets/fonts/
      - assets/fonts/roboto/

  cupertino_icons: ^1.0.8

dev_dependencies:
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.6.0
  flutter_lints: ^4.0.0
  injectable_generator: ^2.6.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/logos/
    - assets/images/
    - assets/fonts/roboto/


flutter_intl:
  main_locale: en_US
  class_name: StringText
  enabled: true
